site_name: TZJX2020
site_description: TZJX2020
site_author: TZJX2020 Team
site_url: https://ctf-wiki.org/en/
repo_name: ctf-wiki/ctf-wiki
#repo_url: https://github.com/ctf-wiki/ctf-wiki
#edit_uri: blob/master/docs/zh/docs/
copyright: Copyright &copy; 2020 TZJX2020 Team
dev_addr: '127.0.0.1:8000' #默认值
theme:
  name: material
  language: en
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: https://tvax1.sinaimg.cn/crop.103.49.982.982.180/6b841424ly8gdi44jokpkj20vi0tjdt1.jpg?KID=imgbed,tva&Expires=1623002005&ssig=VmedXegOCi
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
    
